spring.application.name=webchat

spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username=postgres
spring.datasource.password=19091701

# Hibernate ddl-auto (update, create, create-drop, validate, none)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true